/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SingleDidoPanel.java
 *
 * Created on 12-gen-2010, 10.43.33
 */

package nodes.gui;

/**
 *
 * @author amirrix
 */
public class SingleDidoPanel extends javax.swing.JPanel {

    /** Creates new form SingleDidoPanel */
    public SingleDidoPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblChannel = new javax.swing.JLabel();
        txtChannel = new javax.swing.JTextField();
        checkNO = new javax.swing.JCheckBox();
        checkStep = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        txtStatus = new javax.swing.JTextField();
        btnChange = new javax.swing.JButton();

        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(raspyprog.RaspyProgApp.class).getContext().getResourceMap(SingleDidoPanel.class);
        lblChannel.setText(resourceMap.getString("lblChannel.text")); // NOI18N
        lblChannel.setName("lblChannel"); // NOI18N

        txtChannel.setColumns(3);
        txtChannel.setEditable(false);
        txtChannel.setText(resourceMap.getString("txtChannel.text")); // NOI18N
        txtChannel.setName("txtChannel"); // NOI18N

        checkNO.setText(resourceMap.getString("checkNO.text")); // NOI18N
        checkNO.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        checkNO.setName("checkNO"); // NOI18N

        checkStep.setText(resourceMap.getString("checkStep.text")); // NOI18N
        checkStep.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        checkStep.setName("checkStep"); // NOI18N

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        txtStatus.setColumns(2);
        txtStatus.setEditable(false);
        txtStatus.setText(resourceMap.getString("txtStatus.text")); // NOI18N
        txtStatus.setName("txtStatus"); // NOI18N

        btnChange.setText(resourceMap.getString("btnChange.text")); // NOI18N
        btnChange.setName("btnChange"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblChannel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtChannel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkNO)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkStep)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnChange)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblChannel)
                    .addComponent(txtChannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkNO)
                    .addComponent(checkStep)
                    .addComponent(jLabel1)
                    .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChange))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnChange;
    public javax.swing.JCheckBox checkNO;
    public javax.swing.JCheckBox checkStep;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel lblChannel;
    public javax.swing.JTextField txtChannel;
    public javax.swing.JTextField txtStatus;
    // End of variables declaration//GEN-END:variables

}
